language : node_js
node_js : 
- "node"
script:
- "npm run build"
- "npm run cover"
settings: 
    build_pushes: true
addons:
  code_climate:
    repo_token: 06efb4ff6ca3401937c9dcbf98c54b1fb8cb9978a368bb9e2ea9f5ba0440bfd9
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run coverage
